name= input("Enter you full name: ")
phone=input("Enter your phone number: ")
result=len(name)
Result=name.find("i")
Reverse=name.rfind("s")
capital=name.capitalize()
capitalAll=name.upper()
digits=name.isdigit()
alpha=name.isalpha()
phone_count=phone.count("-")
replace=phone.replace("-", " ")

print("The length of the name is:", result)
print("The index of the first occurrence of 'i' is:", Result)
print("The index of the last occurrence of 's' is:", Reverse)
print("The name with the first letter capitalized is:", capital)
print("The name in all uppercase is:", capitalAll)
print("Is the name composed of only digits?", digits)
print("Is the name composed of only alphabetic characters?", alpha)
print("The number of dashes in the phone number is:", phone_count)
print("The phone number with dashes replaced by spaces is:", replace)
